FROM 863817130246.dkr.ecr.us-east-1.amazonaws.com/repo-moodle:ic360-moodle-base-forked_latest
USER root

# Create all directories in one layer
RUN mkdir -p \
    /var/www/moodledata \
    /etc/cron.d \
    /var/spool/cron/crontabs \
    /var/log/supervisor \
    /var/run/supervisor \
    /var/www/html/local/customlog/{classes,db} && \
    chown www-data:www-data /var/www/moodledata && \
    chmod -R 777 /var/log/supervisor /var/run/supervisor && \
    chmod -R 755 /var/www/html/local

# Clone Moodle and set permissions
#RUN git clone --branch MOODLE_405_STABLE --depth 1 https://github.com/moodle/moodle.git && \
#    cp -a moodle/. /var/www/html/ && \
#    chown -R www-data:www-data /var/www/html && \
#    chmod -R 755 /var/www/html && \
#    rm -rf moodle

# Copy Moodle files from the current directory
COPY --chown=www-data:www-data . /var/www/html/

# Copy system configuration files
COPY --chown=www-data:www-data ic360_configs/nginx/nginx-config.conf /etc/nginx/nginx.conf
COPY --chown=www-data:www-data ic360_configs/nginx/default.conf /etc/nginx/sites-enabled/default
COPY --chown=www-data:www-data ic360_configs/supervisor/supervisor.conf /etc/supervisor/conf.d/services.conf
COPY --chown=www-data:www-data ic360_configs/php/php-config.ini /usr/local/etc/php/conf.d/moodle.ini
COPY --chown=www-data:www-data ic360_configs/php/config.php /var/www/html/config.php
COPY --chown=www-data:www-data ic360_configs/redis/redis.conf /etc/sysctl.d/redis.conf

# Copy and setup scripts
COPY --chown=www-data:www-data ic360_configs/scripts/waitforit.sh /usr/local/bin/
COPY --chown=www-data:www-data ic360_configs/scripts/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh /usr/local/bin/waitforit.sh

# Copy custom Moodle configurations
COPY --chown=www-data:www-data ic360_configs/custom/version.php /var/www/html/local/customlog/
COPY --chown=www-data:www-data ic360_configs/custom/log_handler.php /var/www/html/local/customlog/classes/
COPY --chown=www-data:www-data ic360_configs/custom/observer.php /var/www/html/local/customlog/classes/
COPY --chown=www-data:www-data ic360_configs/custom/events.php /var/www/html/local/customlog/db/

# Set up permissions and configurations
RUN chmod 0644 /etc/cron.d && \
    chmod 644 /etc/supervisor/conf.d/services.conf && \
    touch /var/run/crond.pid && \
    chmod 777 /var/run/crond.pid && \
    chmod 777 /var/spool/cron/crontabs

# Set up sudo access for www-data
RUN echo 'www-data ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/91-www-data && \
    chown root:root /etc/sudoers.d/91-www-data && \
    chmod 440 /etc/sudoers.d/91-www-data

# Switch to www-data user
USER www-data

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
